# Generated by Django 6.0.1 on 2026-01-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_connaissance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeitem',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='knowledge_attachments/'),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='video_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='knowledgeitem',
            name='author',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
