# Generated by Django 6.0.1 on 2026-02-01 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_connaissance', '0003_userprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('categorie', models.CharField(blank=True, default='', max_length=60)),
                ('niveau', models.CharField(blank=True, default='', max_length=40)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='entreprise_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=140)),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('duree_jours', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['plan', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='PlanIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, default='')),
                ('duree_estimee_jours', models.PositiveIntegerField(default=0, help_text='Durée estimée en jours')),
            ],
            options={
                'ordering': ['titre'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.CharField(blank=True, default='', max_length=280),
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='numero_version',
            field=models.CharField(default='1.0', help_text='Ex: 1.0, 2024, v2', max_length=40),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='rejection_comment',
            field=models.TextField(blank=True, default='', help_text='Commentaire du manager en cas de rejet'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_embauche',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='type_contrat',
            field=models.CharField(blank=True, choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('stage', 'Stage')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='knowledgeitem',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('in_review', 'En validation'), ('published', 'Publié'), ('rejected', 'Rejeté'), ('archived', 'Archivé')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='competences',
            field=models.ManyToManyField(blank=True, related_name='knowledge_items', to='app_connaissance.competence'),
        ),
        migrations.AddField(
            model_name='department',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='app_connaissance.entreprise'),
        ),
        migrations.CreateModel(
            name='ModuleKnowledgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('knowledge_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_links', to='app_connaissance.knowledgeitem')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_links', to='app_connaissance.module')),
            ],
            options={
                'ordering': ['module', 'ordre'],
            },
        ),
        migrations.AddField(
            model_name='module',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='app_connaissance.planintegration'),
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('competences', models.ManyToManyField(blank=True, related_name='postes', to='app_connaissance.competence')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postes', to='app_connaissance.department')),
                ('plan_integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postes', to='app_connaissance.planintegration')),
            ],
            options={
                'ordering': ['intitule'],
                'unique_together': {('department', 'intitule')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='app_connaissance.poste'),
        ),
        migrations.CreateModel(
            name='KnowledgeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_version', models.CharField(max_length=40)),
                ('content', models.TextField(blank=True, default='')),
                ('author_name', models.CharField(blank=True, default='', max_length=120)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_actuelle', models.BooleanField(default=False)),
                ('note_modification', models.TextField(blank=True, default='')),
                ('knowledge_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='app_connaissance.knowledgeitem')),
            ],
            options={
                'ordering': ['-date_creation'],
                'unique_together': {('knowledge_item', 'numero_version')},
            },
        ),
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage', models.PositiveSmallIntegerField(default=0)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('certifie', 'Certifié')], default='en_cours', max_length=20)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='app_connaissance.planintegration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_fin'],
                'unique_together': {('user', 'plan')},
            },
        ),
    ]
