# Generated by Django 6.0.1 on 2026-02-02 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_connaissance', '0005_add_userprofile_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeitem',
            name='author_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_knowledge_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Résumé court de la connaissance (une phrase).', max_length=500),
        ),
    ]
