# Generated by Django 6.0.1 on 2026-02-02 12:01

from django.db import migrations


def backfill_versions(apps, schema_editor):
    KnowledgeItem = apps.get_model("app_connaissance", "KnowledgeItem")
    KnowledgeVersion = apps.get_model("app_connaissance", "KnowledgeVersion")
    for item in KnowledgeItem.objects.all():
        if not KnowledgeVersion.objects.filter(knowledge_item=item).exists():
            KnowledgeVersion.objects.create(
                knowledge_item=item,
                numero_version=item.numero_version or "1.0",
                content=item.content or "",
                author_name=item.author or "",
                est_actuelle=True,
            )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("app_connaissance", "0006_add_description_author_user"),
    ]

    operations = [
        migrations.RunPython(backfill_versions, noop),
    ]
