# Generated by Django 6.0.1 on 2026-02-02 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_connaissance', '0008_add_quiz_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='app_connaissance.module')),
            ],
            options={
                'ordering': ['module', 'ordre'],
                'unique_together': {('module', 'ordre')},
            },
        ),
        migrations.CreateModel(
            name='UserModuleStepCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('module_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='app_connaissance.modulestep')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_step_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'module_step')},
            },
        ),
    ]
