# Generated by Django 5.2 on 2026-02-03 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_connaissance", "0009_add_module_steps"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgeitem",
            name="quiz",
            field=models.OneToOneField(
                blank=True,
                help_text="Quiz associé à cette connaissance.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="knowledge_item",
                to="app_connaissance.quiz",
            ),
        ),
    ]
