# Generated by Django 6.0.1 on 2026-02-03 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_connaissance', '0009_add_module_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='knowledge_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='app_connaissance.knowledgeitem'),
        ),
    ]
